AWSTemplateFormatVersion: 2010-09-09
Description: Application Cluster

Resources:

  MyTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apis
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinition:
        - Name: echo-service
          Image: 638549550445.dkr.ecr.us-east-2.amazonaws.com/http-echo-service:latest
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: apis
              awslogs-region: AWS::REGION
              awslogs-stream-prefix: http-go

  MyFargateService:
    Type: AWS::ECS::Service
    DependsOn: ListenerRule
    Properties:
      TaskDefinition: !Ref MyTask
      Cluster: !ImportValue ECSCluster
      LaunchType: FARGATE
      DesireCounts: 2
      DeploymentConfiguration:
        MaximunPercent: 200
        MinimunPercent: 70
      NetworlConfiguration:
        AwsvpcConfiguration:
          AssingPublicIp: ENABLED
          Subnets:
            - !ImportValue Subnet1
            - !ImportValue Subnet2
          SecurityGroup:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: echo-service
          ContainerPort: 8000
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue VPC
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /echo
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue Listener
      Priority: 2
      Condition:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

Outputs:

  ApiEndpoint:
    Description: Base API Endpoint
    Value: !Join ['', ['http://',!ImportValue DNS,'/']]
    Export: 
      Name: ApiEndpoint