AWSTemplateFormatVersion: 2010-09-09
Description: Application Cluster

Resources:

  MyTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: apis
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !ImportValue ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: echo-service
          Image: 638549550445.dkr.ecr.us-east-2.amazonaws.com/http-echo-service:latest
          
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: GO-API-SERVICE
              awslogs-region: us-east-2
              awslogs-stream-prefix: http-go
          Environment:
            - Name: dbusername
              Value: 
            - Name: dbpassword
              Value: 
            - Name: dbhostname
              Value: 
            - Name: dbport
              Value: 
            - Name: httplistenerport
              Value: 
            - Name: databasename
              Value: 

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue VPCID
      Port: 80
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 20
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 10
      HealthyThresholdCount: 10
      TargetType: ip

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !ImportValue LoadBalancerListener
      Priority: 2
      Conditions:
        - Field: path-pattern
          Values:
            - /*
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward

  MyFargateService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: !Ref MyTask
      Cluster: !ImportValue ECSCluster
      LaunchType: FARGATE
      DesiredCount: 2
      DeploymentConfiguration:
        MaximumPercent: 100
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue Subnet1
            - !ImportValue Subnet2
          SecurityGroups:
            - !ImportValue ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: echo-service
          ContainerPort: 8000
          TargetGroupArn: !Ref TargetGroup



Outputs:

  ApiEndpoint:
    Description: Base API Endpoint
    Value: !Join ['', ['http://',!ImportValue DNS,'/']]
    Export: 
      Name: ApiEndpoint