AWSTemplateFormatVersion: 2010-09-09
Description: Application Cluster

Resources:


  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: http-fargate-go

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: LoadBalancer
      Subnets:
       - !ImportValue 'Subnet1'
       - !ImportValue 'Subnet2'
      SecurityGroups:
        - !Ref  LoadBalancerSG

  LoadBalancerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup
      VpcId: !ImportValue 'VPCID'
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  DefaultTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: default
      VpcId: !ImportValue 'VPCID'
      Protocol: 'HTTP'
      Port: 80

  CloudWatchLogsGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: 'GO-API-SERVICE'
      RetentionInDays: 1

  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup
      VpcId: !ImportValue 'VPCID'
      SecurityGroupIngress:
        - IpProtocol: -1
          SourceSecurityGroupId: !Ref 'LoadBalancerSG'

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: LoadBalancer
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Order: 2
          Type: forward
          TargetGroupArn: !Ref DefaultTargetGroup


Outputs:

  Cluster:
    Description: Cluster
    Value: !Ref ECSCluster
    Export: 
      Name: 'ECSCluster'

  Listener:
    Description: LoadBalancerListener
    Value: !Ref LoadBalancerListener
    Export: 
      Name: 'LoadBalancerListener'

  ContainerSecurityGroup:
    Description: ContainerSecurityGroup
    Value: !Ref ContainerSecurityGroup
    Export: 
      Name: 'ContainerSecurityGroup'

  LoadBalanceDNS:
    Description: Cluster
    Value: !GetAtt LoadBalancer.DNSName
    Export: 
      Name: 'DNS'
  
  LogWatchArn:
    Description: LOGwATCH GROUP
    Value: !Ref CloudWatchLogsGroup
    Export: 
      Name: 'LogWatchArn'