
AWSTemplateFormatVersion: 2010-09-09
Description: CloudWatch stream log cluster

Resources:

  SlowLogGroupLogStream: 
    Type: AWS::Logs::LogStream
    Properties: 
      LogGroupName: !ImportValue ClusterLogName
      LogStreamName: slow-stream


  ElasticsearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      ElasticsearchVersion: '7.10'
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        InstanceCount: '2'
        ZoneAwarenessEnabled: true
        InstanceType: 't3.small.elasticsearch'
        DedicatedMasterType: 't3.small.elasticsearch'
        DedicatedMasterCount: '3'
      AccessPolicies:
            Version: '2012-10-17'        
            Statement:
              -
                Effect: 'Allow'
                Principal:
                  Service:  "es.amazonaws.com"
                Action:
                - logs:PutLogEvents
                - logs:CreateLogStream
                Resource: !ImportValue LogWatchArn
      LogPublishingOptions:
        ES_APPLICATION_LOGS: 
            CloudWatchLogsLogGroupArn: !ImportValue LogWatchArn
            Enabled: true
        SEARCH_SLOW_LOGS:
            CloudWatchLogsLogGroupArn: !ImportValue LogWatchArn
            Enabled: true
        INDEX_SLOW_LOGS:
            CloudWatchLogsLogGroupArn: !ImportValue LogWatchArn
            Enabled: true
      EBSOptions:
        EBSEnabled: true
        Iops: '0'
        VolumeSize: '20'
        VolumeType: 'gp2'
      
      AdvancedOptions:
        rest.action.multi.allow_explicit_index: true



